name: healthy_everyday

on:
  push:
    branches: action
  schedule:
    - cron: '15 17 * * *'

jobs:

  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Python3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install Selenium
        run: |
          python -m pip install --upgrade pip
          pip install selenium
      - name: Install Google Chrome
        run: |
          chmod +x ./InstallChrome.sh
          ./InstallChrome.sh
      - name: Run Code
        env:
          ACTION_USERNAME: ${{ secrets.ACTION_USERNAME }}
          ACTION_PASSWORD: ${{ secrets.ACTION_PASSWORD }}
        run: |
          python healthy_everyday_action.py
